/*
Copyright 2023 The Sigstore Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
export const certificates = {
  root: `-----BEGIN CERTIFICATE-----
  MIIBzTCCAVOgAwIBAgIUYcwp7HLy4oRYoMMwt+jUA1f6/p4wCgYIKoZIzj0EAwMw
  JjETMBEGA1UECgwKZm9vYmFyLmRldjEPMA0GA1UEAwwGZm9vYmFyMB4XDTkwMDEw
  MTAwMDAwMFoXDTQwMDEwMTAwMDAwMFowJjETMBEGA1UECgwKZm9vYmFyLmRldjEP
  MA0GA1UEAwwGZm9vYmFyMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE93Ne0YYOCj7I
  JGEn/SdtPXhEQLMBoF8VQd8jzg+RtR0JB4SqRw4YiU6Ms8P+pywl5uXA4dXK65Xq
  yXBAnvqoIIOD/F6rqc0oPecI2Q+qNC+WfhAPrABTe2HD/fiUm7pOo0IwQDAdBgNV
  HQ4EFgQUWjVEZ39pYrDjAokrPUcF7TE3g+owDwYDVR0TAQH/BAUwAwEB/zAOBgNV
  HQ8BAf8EBAMCAQYwCgYIKoZIzj0EAwMDaAAwZQIwfHXFzEIfSuFpY4Np3iCQVe20
  UXDUsZd8kBfoC4nSR2tmzLXfakRE4lJrDpApZSddAjEAmEp+i93OpjdcppPVklbJ
  0d4oLqCCEiykfCaKGoPe6eT/l9Ip1Ufe3fth/Qf5ZDwS
  -----END CERTIFICATE-----`,

  intermediate: `-----BEGIN CERTIFICATE-----
  MIIB8jCCAXigAwIBAgIUGgXM883oo5AKvnltwUHySW/eaQQwCgYIKoZIzj0EAwMw
  JjETMBEGA1UECgwKZm9vYmFyLmRldjEPMA0GA1UEAwwGZm9vYmFyMB4XDTkwMDEw
  MTAwMDAwMFoXDTQwMDEwMTAwMDAwMFowMzETMBEGA1UECgwKZm9vYmFyLmRldjEc
  MBoGA1UEAwwTZm9vYmFyLWludGVybWVkaWF0ZTB2MBAGByqGSM49AgEGBSuBBAAi
  A2IABL7slLvHIJ7hFDckvhNxssGcKhz9uektKJxpjOJbpJRzYrurKTXqvwp+rw0H
  5La/gVPeSa52rsi4f/v3SJhlmrdnLLqFv5DHmL9tOjX8QZ64ExkZS/LD3Gnm4YND
  4grDbKNaMFgwHQYDVR0OBBYEFJEun/IAIfi7kOhDUcOk1mmr/WZrMA4GA1UdDwEB
  /wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMBMGA1UdJQQMMAoGCCsGAQUFBwMD
  MAoGCCqGSM49BAMDA2gAMGUCMQC3LKOXUS9w1c/FHuxVCY2dMm/KbuqPbyVqFqSH
  9GqkMdc1QEfca45ETBluST16L60CMBDWMMldIHz3rpBaqqHiXu5lOEW+5HtxX3ku
  HeHIOtAOwCsfuUt6xcwEtS+G7wtTog==
  -----END CERTIFICATE-----`,

  leaf: `-----BEGIN CERTIFICATE-----
  MIIB8TCCAXegAwIBAgIUBHcWnSa4N1K+z/dRDitfwGT6RUowCgYIKoZIzj0EAwMw
  MzETMBEGA1UECgwKZm9vYmFyLmRldjEcMBoGA1UEAwwTZm9vYmFyLWludGVybWVk
  aWF0ZTAeFw05MDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMAAwWTATBgcqhkjO
  PQIBBggqhkjOPQMBBwNCAARSG+kx7P0C96xegjJgg81uJrJf/G+yYLRKucwP3AMP
  Q1xFB+/8wdUqeTLZPI7AsmcGtvbT/Vr5GRPNT1NUSlFVo4GbMIGYMB0GA1UdDgQW
  BBTXA23F2RNNOlWky1b9MQ1AX3NfQzAfBgNVHSMEGDAWgBSRLp/yACH4u5DoQ1HD
  pNZpq/1mazAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwMQYD
  VR0RBCowKIYRaHR0cDovL2Zvb2Jhci5kZXagEwYKKwYBBAGDvzABB6AFDANGT08w
  CgYIKoZIzj0EAwMDaAAwZQIwWi7Kx/jf8O3riw+dLxK2p4+JPbH92aFrq3WozDex
  iXb1ZTM3FhaFFrM15gMKWlVhAjEAig8qoM7nW0cPq0x029VvJPjm4knz7ZvmnY3d
  VwmStvcPrB+2+tmxDfK1BKl1v5/Z
  -----END CERTIFICATE-----`,

  poisoned: `-----BEGIN CERTIFICATE-----
  MIICCTCCAZCgAwIBAgIUCvg3L1/s7kJJeXNczeKhB8Hno3wwCgYIKoZIzj0EAwMw
  MzETMBEGA1UECgwKZm9vYmFyLmRldjEcMBoGA1UEAwwTZm9vYmFyLWludGVybWVk
  aWF0ZTAeFw05MDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMCYxEzARBgNVBAoM
  CmZvb2Jhci5kZXYxDzANBgNVBAMMBnBvaXNvbjBZMBMGByqGSM49AgEGCCqGSM49
  AwEHA0IABFIb6THs/QL3rF6CMmCDzW4msl/8b7JgtEq5zA/cAw9DXEUH7/zB1Sp5
  Mtk8jsCyZwa29tP9WvkZE81PU1RKUVWjgY4wgYswHQYDVR0OBBYEFNcDbcXZE006
  VaTLVv0xDUBfc19DMB8GA1UdIwQYMBaAFJEun/IAIfi7kOhDUcOk1mmr/WZrMA8G
  A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUF
  BwMDMBMGCisGAQQB1nkCBAMBAf8EAgUAMAoGCCqGSM49BAMDA2cAMGQCMC4tbV94
  3hZRTkTXgA6HmkNBboDXMzovvckK9CYVwtB26SSGkqeyTNLDZVrSEUsNtAIwaWIg
  FWUrgRgx/VRQa/615oJIN5zpNL8eBy27TfZ0uMMhj2+LKObw+h4ojXvlQfFe
  -----END CERTIFICATE-----`,

  // Leaf cert w/ no SAN extension
  nosan: `-----BEGIN CERTIFICATE-----
  MIIB9TCCAXqgAwIBAgIUIGoY+IIBlw7a9HjszFBweM1eEvYwCgYIKoZIzj0EAwMw
  MzETMBEGA1UECgwKZm9vYmFyLmRldjEcMBoGA1UEAwwTZm9vYmFyLWludGVybWVk
  aWF0ZTAeFw05MDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMCUxEzARBgNVBAoM
  CmZvb2Jhci5kZXYxDjAMBgNVBAMMBW5vc2FuMFkwEwYHKoZIzj0CAQYIKoZIzj0D
  AQcDQgAEUhvpMez9AvesXoIyYIPNbiayX/xvsmC0SrnMD9wDD0NcRQfv/MHVKnky
  2TyOwLJnBrb20/1a+RkTzU9TVEpRVaN6MHgwHQYDVR0OBBYEFNcDbcXZE006VaTL
  Vv0xDUBfc19DMB8GA1UdIwQYMBaAFJEun/IAIfi7kOhDUcOk1mmr/WZrMA4GA1Ud
  DwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzARBgorBgEEAYO/MAEBBANG
  T08wCgYIKoZIzj0EAwMDaQAwZgIxAOtXGjLqLNETvHpD9O7huHgMJUfyX50+MRsz
  Esm0CTzCbfub4/MxpcCmAKiMwsQCxgIxAKCnDR7WhdMe+ZgUU4655SehtDpVrYkf
  BI9OIACkwPLcKCRFnDFOLQ7cHh1RwlTofw==
  -----END CERTIFICATE-----`,

  // Leaf cert w/o a key usage extension.
  nokeyusage: `-----BEGIN CERTIFICATE-----
  MIIBvDCCAUOgAwIBAgIUIG/3EHqpwGJ0AZOgVZZSs8zuYdIwCgYIKoZIzj0EAwMw
  MzETMBEGA1UECgwKZm9vYmFyLmRldjEcMBoGA1UEAwwTZm9vYmFyLWludGVybWVk
  aWF0ZTAeFw05MDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMAAwWTATBgcqhkjO
  PQIBBggqhkjOPQMBBwNCAARSG+kx7P0C96xegjJgg81uJrJf/G+yYLRKucwP3AMP
  Q1xFB+/8wdUqeTLZPI7AsmcGtvbT/Vr5GRPNT1NUSlFVo2gwZjAdBgNVHQ4EFgQU
  1wNtxdkTTTpVpMtW/TENQF9zX0MwHwYDVR0jBBgwFoAUkS6f8gAh+LuQ6ENRw6TW
  aav9ZmswEwYDVR0lBAwwCgYIKwYBBQUHAwMwDwYDVR0RBAgwBocEwKgBATAKBggq
  hkjOPQQDAwNnADBkAjBaTd4G95x360ASUvn8OsrCebFBn+g1V9MiMcAZGqxvt6Bz
  LKuszDELLujHMRLVhK4CMCI+SW+AUNqerFkF0AeUIjZHJ5IypmOhaiAYx+rSD73g
  fhfTGQv5PWHeyW7rvAGx8Q==
  -----END CERTIFICATE-----`,

  // Leaf cert which was signed by another leaf certificate.
  invalidleaf: `-----BEGIN CERTIFICATE-----
  MIIBijCCAS+gAwIBAgIUay2QH/yn7biKcZIG3ngAAJ1UIDswCgYIKoZIzj0EAwMw
  ADAeFw05MDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMAAwWTATBgcqhkjOPQIB
  BggqhkjOPQMBBwNCAATQS7/83FBWZHvsR6pqC9S13E7+cXeyACaTaeZ/q7QT9KLM
  Z4V3B5HIZpCF8uYbSG570bxDZPNLasDgH4YaN0rdo4GGMIGDMB0GA1UdDgQWBBTl
  VbnUsc5wOUOk6dm9VKhDo4+T7TAfBgNVHSMEGDAWgBTXA23F2RNNOlWky1b9MQ1A
  X3NfQzAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHAYDVR0R
  BBUwE4YRaHR0cDovL2Zvb2Jhci5kZXYwCgYIKoZIzj0EAwMDSQAwRgIhAK4F+zVs
  ihy1Jz7xHResesgWpDn8ymbk36z5Iu0XZPx2AiEAiK9Rmcl6BqdI6UCfDeXdCPaL
  X+LFBrV+0VdjR5jl17g=
  -----END CERTIFICATE-----`,

  // Unauthorized intermediate cert which was signed by 'intermediate'
  // above. This cert is not authorized due to the fact that the
  // issuing cert has a pathlen:0 constraint.
  invalidint: `-----BEGIN CERTIFICATE-----
  MIICCzCCAZGgAwIBAgIUGdCThOLeJHfzGnsFYQzqrDPxQqAwCgYIKoZIzj0EAwMw
  MzETMBEGA1UECgwKZm9vYmFyLmRldjEcMBoGA1UEAwwTZm9vYmFyLWludGVybWVk
  aWF0ZTAeFw05MDAxMDEwMDAwMDBaFw00MDAxMDEwMDAwMDBaMDsxEzARBgNVBAoM
  CmZvb2Jhci5kZXYxJDAiBgNVBAMMG2Zvb2Jhci1pbnZhbGlkLWludGVybWVkaWF0
  ZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNBLv/zcUFZke+xHqmoL1LXcTv5x
  d7IAJpNp5n+rtBP0osxnhXcHkchmkIXy5htIbnvRvENk80tqwOAfhho3St2jezB5
  MB0GA1UdDgQWBBTlVbnUsc5wOUOk6dm9VKhDo4+T7TAfBgNVHSMEGDAWgBSRLp/y
  ACH4u5DoQ1HDpNZpq/1mazAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB
  /wIBADATBgNVHSUEDDAKBggrBgEFBQcDAzAKBggqhkjOPQQDAwNoADBlAjEA/XMQ
  omRjxkN7dApOGQ9rD1yF9oBNDKrWI4Pe90pkMpkn5/jPoMnqABPDkakBYJh5AjAu
  yD/zS+yrv7qbzB5Jumi/T9El3fYz7mpW8INtwHg/d0BrO9Mkt/mkTjiEjeX6AoI=
  -----END CERTIFICATE-----`,

  // Leaf which was issued by the invalid intermediate cert above and
  // violates the pathlen:0 constraint of the true intermediate.
  deepleaf: `-----BEGIN CERTIFICATE-----
  MIIB2TCCAX+gAwIBAgIUdE9ALIE7nFHMkrZV51ZMmLlGFrQwCgYIKoZIzj0EAwMw
  OzETMBEGA1UECgwKZm9vYmFyLmRldjEkMCIGA1UEAwwbZm9vYmFyLWludmFsaWQt
  aW50ZXJtZWRpYXRlMB4XDTkwMDEwMTAwMDAwMFoXDTQwMDEwMTAwMDAwMFowADBZ
  MBMGByqGSM49AgEGCCqGSM49AwEHA0IABFIb6THs/QL3rF6CMmCDzW4msl/8b7Jg
  tEq5zA/cAw9DXEUH7/zB1Sp5Mtk8jsCyZwa29tP9WvkZE81PU1RKUVWjgZswgZgw
  HQYDVR0OBBYEFNcDbcXZE006VaTLVv0xDUBfc19DMB8GA1UdIwQYMBaAFOVVudSx
  znA5Q6Tp2b1UqEOjj5PtMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEF
  BQcDAzAxBgNVHREEKjAohhFodHRwOi8vZm9vYmFyLmRldqATBgorBgEEAYO/MAEH
  oAUMA0ZPTzAKBggqhkjOPQQDAwNIADBFAiEA4Mo94nfLm+Tppp4s2TT/fgc3bJnD
  STIQAJ48P98hceMCIHwwDrjqaQJNUNV3BwlEMc1DYkHo2p4IZf6zXi+Aasih
  -----END CERTIFICATE-----`,

  fulcioleaf: `-----BEGIN CERTIFICATE-----
  MIIG8TCCBnegAwIBAgIUevNhYKseJ5CvrJuazByfceokHxIwCgYIKoZIzj0EAwMw
  NzEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MR4wHAYDVQQDExVzaWdzdG9yZS1pbnRl
  cm1lZGlhdGUwHhcNMjMwNDA0MTUxNzU0WhcNMjMwNDA0MTUyNzU0WjAAMFkwEwYH
  KoZIzj0CAQYIKoZIzj0DAQcDQgAEGjx8Z0dJ11Xe3ywTYQ0je5NwEL+vO2R4a4F5
  T/i7VTxLmqM4gGFrt2PrqUg4w+qAUUaZhg+TPxH6X2wsvTalA6OCBZYwggWSMA4G
  A1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUZi1l
  sBMFvx5tVauoJNO1OKRlneQwHwYDVR0jBBgwFoAU39Ppz1YkEZb5qNjpKFWixi4Y
  ZD8wcwYDVR0RAQH/BGkwZ4ZlaHR0cHM6Ly9naXRodWIuY29tL25wbS9wcm92ZW5h
  bmNlLXRlc3RzLy5naXRodWIvd29ya2Zsb3dzL3B1Ymxpc2gtd2l0aC1wcm92ZW5h
  bmNlLnltbEByZWZzL2hlYWRzL21haW4wOQYKKwYBBAGDvzABAQQraHR0cHM6Ly90
  b2tlbi5hY3Rpb25zLmdpdGh1YnVzZXJjb250ZW50LmNvbTAfBgorBgEEAYO/MAEC
  BBF3b3JrZmxvd19kaXNwYXRjaDA2BgorBgEEAYO/MAEDBChiOGFkZjBlMmVhNjYz
  ODE4Njc0YjBiNTQyMzY0NjM4ZDAxNjI1NmQ5MCUGCisGAQQBg78wAQQEF3B1Ymxp
  c2gtd2l0aC1wcm92ZW5hbmNlMCIGCisGAQQBg78wAQUEFG5wbS9wcm92ZW5hbmNl
  LXRlc3RzMB0GCisGAQQBg78wAQYED3JlZnMvaGVhZHMvbWFpbjA7BgorBgEEAYO/
  MAEIBC0MK2h0dHBzOi8vdG9rZW4uYWN0aW9ucy5naXRodWJ1c2VyY29udGVudC5j
  b20wdQYKKwYBBAGDvzABCQRnDGVodHRwczovL2dpdGh1Yi5jb20vbnBtL3Byb3Zl
  bmFuY2UtdGVzdHMvLmdpdGh1Yi93b3JrZmxvd3MvcHVibGlzaC13aXRoLXByb3Zl
  bmFuY2UueW1sQHJlZnMvaGVhZHMvbWFpbjA4BgorBgEEAYO/MAEKBCoMKGI4YWRm
  MGUyZWE2NjM4MTg2NzRiMGI1NDIzNjQ2MzhkMDE2MjU2ZDkwHQYKKwYBBAGDvzAB
  CwQPDA1naXRodWItaG9zdGVkMDcGCisGAQQBg78wAQwEKQwnaHR0cHM6Ly9naXRo
  dWIuY29tL25wbS9wcm92ZW5hbmNlLXRlc3RzMDgGCisGAQQBg78wAQ0EKgwoYjhh
  ZGYwZTJlYTY2MzgxODY3NGIwYjU0MjM2NDYzOGQwMTYyNTZkOTAfBgorBgEEAYO/
  MAEOBBEMD3JlZnMvaGVhZHMvbWFpbjAZBgorBgEEAYO/MAEPBAsMCTU2Njc1ODg5
  MTAmBgorBgEEAYO/MAEQBBgMFmh0dHBzOi8vZ2l0aHViLmNvbS9ucG0wFwYKKwYB
  BAGDvzABEQQJDAc2MDc4NzIwMHUGCisGAQQBg78wARIEZwxlaHR0cHM6Ly9naXRo
  dWIuY29tL25wbS9wcm92ZW5hbmNlLXRlc3RzLy5naXRodWIvd29ya2Zsb3dzL3B1
  Ymxpc2gtd2l0aC1wcm92ZW5hbmNlLnltbEByZWZzL2hlYWRzL21haW4wOAYKKwYB
  BAGDvzABEwQqDChiOGFkZjBlMmVhNjYzODE4Njc0YjBiNTQyMzY0NjM4ZDAxNjI1
  NmQ5MCEGCisGAQQBg78wARQEEwwRd29ya2Zsb3dfZGlzcGF0Y2gwWgYKKwYBBAGD
  vzABFQRMDEpodHRwczovL2dpdGh1Yi5jb20vbnBtL3Byb3ZlbmFuY2UtdGVzdHMv
  YWN0aW9ucy9ydW5zLzQ2MDk0Mzc4ODEvYXR0ZW1wdHMvMTCBigYKKwYBBAHWeQIE
  AgR8BHoAeAB2AN09MGrGxxEyYxkeHJlnNwKiSl643jyt/4eKcoAvKe6OAAABh0zY
  lJgAAAQDAEcwRQIhANcUpdf/+9z7lj4QjXhBz/qtXRMk8I1+KAHRHv0r4Hu7AiBC
  ucWSm73qO7zqbQbzWIQrBTHAPsEJXIiZ1ApwY4ryUzAKBggqhkjOPQQDAwNoADBl
  AjA+GVmr0h0JgfyWhO8OszLLeK+7l/kUWnSH1TSG5+eIZ9ytfRyVFFJkBzE0WmcL
  rtECMQCDR5Zb2cwiENFL1XGg5E7si96en+Hc/F9EMKjQUHLHWRnMSRukC7jr3GnF
  NWj3tGQ=
  -----END CERTIFICATE-----`,
};
