/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * log entry schema for dsse envelopes
 */
export type DSSESchema = DSSEV001Schema;
/**
 * Schema for DSSE envelopes
 */
export type DSSEV001Schema = DSSEV001Schema1 & DSSEV001Schema2;
export type DSSEV001Schema2 = {
  [k: string]: unknown;
};

export interface DSSEV001Schema1 {
  proposedContent?: {
    /**
     * DSSE envelope specified as a stringified JSON object
     */
    envelope: string;
    /**
     * collection of all verification material (e.g. public keys or certificates) used to verify signatures over envelope's payload, specified as base64-encoded strings
     *
     * @minItems 1
     */
    verifiers: [string, ...string[]];
  };
  /**
   * extracted collection of all signatures of the envelope's payload; elements will be sorted by lexicographical order of the base64 encoded signature strings
   *
   * @minItems 1
   */
  signatures?: [
    {
      /**
       * base64 encoded signature of the payload
       */
      signature: string;
      /**
       * verification material that was used to verify the corresponding signature, specified as a base64 encoded string
       */
      verifier: string;
    },
    ...{
      /**
       * base64 encoded signature of the payload
       */
      signature: string;
      /**
       * verification material that was used to verify the corresponding signature, specified as a base64 encoded string
       */
      verifier: string;
    }[]
  ];
  /**
   * Specifies the hash algorithm and value encompassing the entire envelope sent to Rekor
   */
  envelopeHash?: {
    /**
     * The hashing function used to compute the hash value
     */
    algorithm: "sha256";
    /**
     * The value of the computed digest over the entire envelope
     */
    value: string;
  };
  /**
   * Specifies the hash algorithm and value covering the payload within the DSSE envelope
   */
  payloadHash?: {
    /**
     * The hashing function used to compute the hash value
     */
    algorithm: "sha256";
    /**
     * The value of the computed digest over the payload within the envelope
     */
    value: string;
  };
}
