name: "Conformance tests"

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: "45 7 * * 1"

permissions:
  contents: read

jobs:
  conformance-production:
    name: Conformance Test (Production)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: npm run build
    - uses: sigstore/sigstore-conformance@21533cde107c734ebc153c3e3a24d75fc9811a36 # v0.0.29
      with:
        entrypoint: ${{ github.workspace }}/packages/conformance/bin/run

  conformance-staging:
    name: Conformance Test (Staging)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Build sigstore-js
      run: npm run build
    - uses: sigstore/sigstore-conformance@21533cde107c734ebc153c3e3a24d75fc9811a36 # v0.0.29
      with:
        entrypoint: ${{ github.workspace }}/packages/conformance/bin/run
        environment: staging
